// Generated by protoc-gen-validate-kt. DO NOT EDIT.
package golden

import dev.bmcreations.protovalidate.FieldViolation
import dev.bmcreations.protovalidate.ValidationResult
import dev.bmcreations.protovalidate.Validators

fun Inner.validate(): ValidationResult {
    val violations = mutableListOf<FieldViolation>()
    Validators.checkStringMinLen(id, 1L, "id")?.let { violations += it }
    return if (violations.isEmpty()) ValidationResult.Valid
           else ValidationResult.Invalid(violations)
}

