// Generated by protoc-gen-validate-kt. DO NOT EDIT.
package golden

import dev.bmcreations.protovalidate.FieldViolation
import dev.bmcreations.protovalidate.ValidationResult
import dev.bmcreations.protovalidate.Validators

fun SingleRequiredOneof.validate(): ValidationResult {
    val violations = mutableListOf<FieldViolation>()
    if (oneCase == SingleRequiredOneof.OneCase.ONE_NOT_SET) {
        violations += FieldViolation("one", "required", "exactly one field is required in oneof")
    }
    Validators.checkRequired(oneCase == SingleRequiredOneof.OneCase.VAL, "val")?.let { violations += it }
    if (oneCase == SingleRequiredOneof.OneCase.VAL) {
        if (hasVal()) {
            `val`.validate().let { result ->
                if (result is ValidationResult.Invalid) {
                    violations += result.violations.map { it.copy(field = if (it.field.isEmpty()) "val" else "val.${it.field}") }
                }
            }
        }
    }
    return if (violations.isEmpty()) ValidationResult.Valid
           else ValidationResult.Invalid(violations)
}

