// Generated by protoc-gen-validate-kt. DO NOT EDIT.
package golden

import dev.bmcreations.protovalidate.FieldViolation
import dev.bmcreations.protovalidate.ValidationResult
import dev.bmcreations.protovalidate.Validators

fun MultiRequiredOneof.validate(): ValidationResult {
    val violations = mutableListOf<FieldViolation>()
    if (scopeCase == MultiRequiredOneof.ScopeCase.SCOPE_NOT_SET) {
        violations += FieldViolation("scope", "required", "exactly one field is required in oneof")
    }
    if (scopeCase == MultiRequiredOneof.ScopeCase.CHAT) {
        Validators.checkRequired(hasChat(), "chat")?.let { violations += it }
        if (hasChat()) {
            chat.validate().let { result ->
                if (result is ValidationResult.Invalid) {
                    violations += result.violations.map { it.copy(field = if (it.field.isEmpty()) "chat" else "chat.${it.field}") }
                }
            }
        }
    }
    if (scopeCase == MultiRequiredOneof.ScopeCase.PROFILE) {
        Validators.checkRequired(hasProfile(), "profile")?.let { violations += it }
        if (hasProfile()) {
            profile.validate().let { result ->
                if (result is ValidationResult.Invalid) {
                    violations += result.violations.map { it.copy(field = if (it.field.isEmpty()) "profile" else "profile.${it.field}") }
                }
            }
        }
    }
    return if (violations.isEmpty()) ValidationResult.Valid
           else ValidationResult.Invalid(violations)
}

