// Generated by protoc-gen-validate-kt. DO NOT EDIT.
package golden

import dev.bmcreations.protovalidate.FieldViolation
import dev.bmcreations.protovalidate.ValidationResult
import dev.bmcreations.protovalidate.Validators

fun OptionalOneof.validate(): ValidationResult {
    val violations = mutableListOf<FieldViolation>()
    if (oCase == OptionalOneof.OCase.VAL) {
        Validators.checkRequired(hasVal(), "val")?.let { violations += it }
        if (hasVal()) {
            `val`.validate().let { result ->
                if (result is ValidationResult.Invalid) {
                    violations += result.violations.map { it.copy(field = if (it.field.isEmpty()) "val" else "val.${it.field}") }
                }
            }
        }
    }
    return if (violations.isEmpty()) ValidationResult.Valid
           else ValidationResult.Invalid(violations)
}

