// Generated by protoc-gen-validate-kt. DO NOT EDIT.
package golden

import dev.bmcreations.protovalidate.FieldViolation
import dev.bmcreations.protovalidate.ValidationResult
import dev.bmcreations.protovalidate.Validators

fun ScalarRulesInOneof.validate(): ValidationResult {
    val violations = mutableListOf<FieldViolation>()
    if (oCase == ScalarRulesInOneof.OCase.X) {
        if (hasX()) {
            Validators.checkStringMinLen(x, 3L, "x")?.let { violations += it }
            Validators.checkStringMaxLen(x, 5L, "x")?.let { violations += it }
        }
    }
    if (oCase == ScalarRulesInOneof.OCase.Y) {
        if (hasY()) {
            Validators.checkGt(y, 0, "y", "int32.gt")?.let { violations += it }
        }
    }
    return if (violations.isEmpty()) ValidationResult.Valid
           else ValidationResult.Invalid(violations)
}

